import { Database } from '../lib/database';

export const mockData: Database = {
  users: [
    {
      id: 1,
      username: "gokul",
      password: "123",
      name: "Gokul",
      email: "gokulnath30@gmail.com",
      region: "North Region",
      employeeId: "AUD001",
      no_of_audits: 25,
      completed_audits: 20,
      avg_audit_time: "45 mins"
    },
    {
      id: 3,
      username: "rahul",
      password: "123",
      name: "Rahul Kumar",
      email: "rahul@example.com",
      region: "East Region",
      employeeId: "AUD003",
      no_of_audits: 30,
      completed_audits: 28,
      avg_audit_time: "42 mins"
    }
  ],
  stores: [
    {
      id: 1,
      storeName: "Mega Mart Downtown",
      address: "123 Main St",
      shopType: "Grocery",
      lastVisited: "2025-11-15 09:12",
      progress: 72,
      period: "Weekly",
      prevStatus: "Audit completed",
      currentStatus: "Missing items",
      indexCode: "1332656",
      seq: 3,
      freq: "Weekly",
      activity: "Stock check",
      time: "09:00 AM",
      mode: "In-person",
      priority: "high",
      assignedUserId: 1,
      assignedUserName: "Gokul",
      region: "North Region"
    },
    {
      id: 2,
      storeName: "Quick Shop Central",
      address: "456 Park Ave",
      shopType: "Convenience",
      lastVisited: "2025-11-16 11:45",
      progress: 40,
      period: "Monthly",
      prevStatus: "Audit completed",
      currentStatus: "In progress",
      indexCode: "1332657",
      seq: 7,
      freq: "Monthly",
      activity: "Planogram",
      time: "11:30 AM",
      mode: "Voice",
      priority: "medium",
      assignedUserId: 1,
      assignedUserName: "Gokul",
      region: "North Region"
    },
    {
      id: 3,
      storeName: "Super Store East",
      address: "789 Oak Rd",
      shopType: "Supermarket",
      lastVisited: "2025-11-13 14:05",
      progress: 95,
      period: "Weekly",
      prevStatus: "Audit completed",
      currentStatus: "Verified",
      indexCode: "1332658",
      seq: 1,
      freq: "Weekly",
      activity: "Sales audit",
      time: "02:00 PM",
      mode: "In-person",
      priority: "low",
      assignedUserId: 1,
      assignedUserName: "Gokul",
      region: "North Region"
    },
    {
      id: 4,
      storeName: "City Mall West",
      address: "321 Central Ave",
      shopType: "Department Store",
      lastVisited: "2025-11-14 10:30",
      progress: 60,
      period: "Monthly",
      prevStatus: "Audit completed",
      currentStatus: "In progress",
      indexCode: "1332659",
      seq: 2,
      freq: "Monthly",
      activity: "Inventory Check",
      time: "10:00 AM",
      mode: "In-person",
      priority: "medium",
      assignedUserId: 2,
      assignedUserName: "Priya Sharma",
      region: "South Region"
    },
    {
      id: 5,
      storeName: "Metro Supercenter",
      address: "654 Market St",
      shopType: "Hypermarket",
      lastVisited: "2025-11-12 16:20",
      progress: 100,
      period: "Weekly",
      prevStatus: "Audit completed",
      currentStatus: "Verified",
      indexCode: "1332660",
      seq: 4,
      freq: "Weekly",
      activity: "Price Audit",
      time: "03:00 PM",
      mode: "Voice",
      priority: "low",
      assignedUserId: 3,
      assignedUserName: "Rahul Kumar",
      region: "East Region"
    }
  ],
  products: [
    {
      id: 1,
      name: "Vitamin A&D Baby Oil 200ml",
      categories: ["Baby Care"],
      brand: "VITAMIN",
      manufacturer: "CDBox",
      containers: 1,
      brands: "VITAMIN",
      category: "Baby Care",
      manufacturers: "CDBox",
      sku: "VIT-001",
      status: "pending",
      lastUpdated: "2 hours ago",
      size: "200ml",
      mrp: 150,
      storeId: 1,
      self_Stock: 0,
      other_Stock: 0,
      retaile_selling_price: 0,
      direct_price: 0,
      indirect_price: 0
    },
    {
      id: 2,
      name: "Baby Powder 100g",
      categories: ["Baby Care"],
      brand: "BabySoft",
      manufacturer: "BabyCare Inc",
      containers: 1,
      brands: "BabySoft",
      category: "Baby Care",
      manufacturers: "BabyCare Inc",
      sku: "BS-002",
      status: "verified",
      lastUpdated: "1 day ago",
      size: "100g",
      mrp: 120,
      storeId: 2,
      self_Stock: 15,
      other_Stock: 8,
      retaile_selling_price: 110,
      direct_price: 85,
      indirect_price: 95
    }
  ]
};