import { Database } from '../lib/database';

export const mockData: Database = {
  users: [
    {
      id: 1,
      username: "gokul",
      password: "123",
      name: "Gokul",
      email: "gokulnath30@gmail.com",
      region: "North Region",
      employeeId: "AUD001",
      no_of_audits: 25,
      completed_audits: 20,
      avg_audit_time: "45 mins"
    },
    {
      id: 3,
      username: "rahul",
      password: "123",
      name: "Rahul Kumar",
      email: "rahul@example.com",
      region: "East Region",
      employeeId: "AUD003",
      no_of_audits: 30,
      completed_audits: 28,
      avg_audit_time: "42 mins"
    }
  ],
  stores: [
    {
      id: 1,
      storeName: "Mega Mart Downtown",
      address: "123 Main St",
      shopType: "Grocery",
      lastVisited: "2025-11-15 09:12",
      progress: 72,
      period: "Weekly",
      prevStatus: "Audit completed",
      currentStatus: "Missing items",
      indexCode: "1332656",
      seq: 3,
      freq: "Weekly",
      activity: "Stock check",
      time: "09:00 AM",
      mode: "In-person",
      priority: "high",
      assignedUserId: 1,
      assignedUserName: "Gokul",
      region: "North Region"
    },
    {
      id: 2,
      storeName: "Quick Shop Central",
      address: "456 Park Ave",
      shopType: "Convenience",
      lastVisited: "2025-11-16 11:45",
      progress: 40,
      period: "Monthly",
      prevStatus: "Audit completed",
      currentStatus: "In progress",
      indexCode: "1332657",
      seq: 7,
      freq: "Monthly",
      activity: "Planogram",
      time: "11:30 AM",
      mode: "Voice",
      priority: "medium",
      assignedUserId: 1,
      assignedUserName: "Gokul",
      region: "North Region"
    },
    {
      id: 3,
      storeName: "Super Store East",
      address: "789 Oak Rd",
      shopType: "Supermarket",
      lastVisited: "2025-11-13 14:05",
      progress: 95,
      period: "Weekly",
      prevStatus: "Audit completed",
      currentStatus: "Verified",
      indexCode: "1332658",
      seq: 1,
      freq: "Weekly",
      activity: "Sales audit",
      time: "02:00 PM",
      mode: "In-person",
      priority: "low",
      assignedUserId: 1,
      assignedUserName: "Gokul",
      region: "North Region"
    },
    {
      id: 4,
      storeName: "City Mall West",
      address: "321 Central Ave",
      shopType: "Department Store",
      lastVisited: "2025-11-14 10:30",
      progress: 60,
      period: "Monthly",
      prevStatus: "Audit completed",
      currentStatus: "In progress",
      indexCode: "1332659",
      seq: 2,
      freq: "Monthly",
      activity: "Inventory Check",
      time: "10:00 AM",
      mode: "In-person",
      priority: "medium",
      assignedUserId: 2,
      assignedUserName: "Priya Sharma",
      region: "South Region"
    },
    {
      id: 5,
      storeName: "Metro Supercenter",
      address: "654 Market St",
      shopType: "Hypermarket",
      lastVisited: "2025-11-12 16:20",
      progress: 100,
      period: "Weekly",
      prevStatus: "Audit completed",
      currentStatus: "Verified",
      indexCode: "1332660",
      seq: 4,
      freq: "Weekly",
      activity: "Price Audit",
      time: "03:00 PM",
      mode: "Voice",
      priority: "low",
      assignedUserId: 3,
      assignedUserName: "Rahul Kumar",
      region: "East Region"
    }
  ],
  products: [
  {
    id: 1,
    name: "Vitamin A&D Baby Oil 200ml",
    categories: ["Baby Care"],
    brand: "VITAMIN",
    manufacturer: "CDBox",
    containers: 1,
    brands: "VITAMIN",
    category: "Baby Care",
    manufacturers: "CDBox",
    sku: "VIT-001",
    status: "pending",
    lastUpdated: "2 hours ago",
    size: "200ml",
    mrp: 150,
    storeId: 1,
    self_Stock: 0,
    other_Stock: 0,
    retaile_selling_price: 0,
    direct_price: 0,
    indirect_price: 0
  },
  {
    id: 2,
    name: "Baby Powder 100g",
    categories: ["Baby Care"],
    brand: "BabySoft",
    manufacturer: "BabyCare Inc",
    containers: 1,
    brands: "BabySoft",
    category: "Baby Care",
    manufacturers: "BabyCare Inc",
    sku: "BS-002",
    status: "verified",
    lastUpdated: "1 day ago",
    size: "100g",
    mrp: 120,
    storeId: 2,
    self_Stock: 15,
    other_Stock: 8,
    retaile_selling_price: 110,
    direct_price: 85,
    indirect_price: 95
  },
  {
    id: 3,
    name: "Gentle Baby Shampoo 150ml",
    categories: ["Baby Care", "Bath"],
    brand: "PureBaby",
    manufacturer: "NaturalCare Ltd",
    containers: 1,
    brands: "PureBaby",
    category: "Baby Care",
    manufacturers: "NaturalCare Ltd",
    sku: "PB-003",
    status: "verified",
    lastUpdated: "3 hours ago",
    size: "150ml",
    mrp: 180,
    storeId: 1,
    self_Stock: 25,
    other_Stock: 12,
    retaile_selling_price: 165,
    direct_price: 130,
    indirect_price: 145
  },
  {
    id: 4,
    name: "Baby Lotion 250ml",
    categories: ["Baby Care", "Skin Care"],
    brand: "SoftTouch",
    manufacturer: "SkinHealth Corp",
    containers: 1,
    brands: "SoftTouch",
    category: "Baby Care",
    manufacturers: "SkinHealth Corp",
    sku: "ST-004",
    status: "pending",
    lastUpdated: "5 hours ago",
    size: "250ml",
    mrp: 220,
    storeId: 3,
    self_Stock: 0,
    other_Stock: 0,
    retaile_selling_price: 0,
    direct_price: 0,
    indirect_price: 0
  },
  {
    id: 5,
    name: "Diaper Rash Cream 100g",
    categories: ["Baby Care", "Medicated"],
    brand: "HealFast",
    manufacturer: "MediCare Products",
    containers: 1,
    brands: "HealFast",
    category: "Baby Care",
    manufacturers: "MediCare Products",
    sku: "HF-005",
    status: "verified",
    lastUpdated: "2 days ago",
    size: "100g",
    mrp: 95,
    storeId: 2,
    self_Stock: 40,
    other_Stock: 22,
    retaile_selling_price: 85,
    direct_price: 65,
    indirect_price: 75
  },
  {
    id: 6,
    name: "Baby Body Wash 200ml",
    categories: ["Baby Care", "Bath"],
    brand: "BubbleBath",
    manufacturer: "CleanKids Inc",
    containers: 1,
    brands: "BubbleBath",
    category: "Baby Care",
    manufacturers: "CleanKids Inc",
    sku: "BB-006",
    status: "verified",
    lastUpdated: "6 hours ago",
    size: "200ml",
    mrp: 160,
    storeId: 1,
    self_Stock: 18,
    other_Stock: 9,
    retaile_selling_price: 145,
    direct_price: 115,
    indirect_price: 130
  },
  {
    id: 7,
    name: "Baby Massage Oil 150ml",
    categories: ["Baby Care"],
    brand: "NaturOil",
    manufacturer: "OrganicWellness",
    containers: 1,
    brands: "NaturOil",
    category: "Baby Care",
    manufacturers: "OrganicWellness",
    sku: "NO-007",
    status: "pending",
    lastUpdated: "1 hour ago",
    size: "150ml",
    mrp: 190,
    storeId: 3,
    self_Stock: 0,
    other_Stock: 0,
    retaile_selling_price: 0,
    direct_price: 0,
    indirect_price: 0
  },
  {
    id: 8,
    name: "Baby Wipes 80pcs",
    categories: ["Baby Care", "Hygiene"],
    brand: "FreshWipe",
    manufacturer: "HygienePlus Ltd",
    containers: 1,
    brands: "FreshWipe",
    category: "Baby Care",
    manufacturers: "HygienePlus Ltd",
    sku: "FW-008",
    status: "verified",
    lastUpdated: "4 days ago",
    size: "80pcs",
    mrp: 75,
    storeId: 2,
    self_Stock: 60,
    other_Stock: 35,
    retaile_selling_price: 65,
    direct_price: 45,
    indirect_price: 55
  },
  {
    id: 9,
    name: "Baby Soap 100g",
    categories: ["Baby Care", "Bath"],
    brand: "GentleClean",
    manufacturer: "SoapMakers Co",
    containers: 1,
    brands: "GentleClean",
    category: "Baby Care",
    manufacturers: "SoapMakers Co",
    sku: "GC-009",
    status: "verified",
    lastUpdated: "12 hours ago",
    size: "100g",
    mrp: 45,
    storeId: 1,
    self_Stock: 75,
    other_Stock: 40,
    retaile_selling_price: 40,
    direct_price: 25,
    indirect_price: 32
  },
  {
    id: 10,
    name: "Baby Hair Oil 100ml",
    categories: ["Baby Care", "Hair Care"],
    brand: "SilkyHair",
    manufacturer: "HairCare Specialists",
    containers: 1,
    brands: "SilkyHair",
    category: "Baby Care",
    manufacturers: "HairCare Specialists",
    sku: "SH-010",
    status: "pending",
    lastUpdated: "8 hours ago",
    size: "100ml",
    mrp: 110,
    storeId: 3,
    self_Stock: 0,
    other_Stock: 0,
    retaile_selling_price: 0,
    direct_price: 0,
    indirect_price: 0
  }
]
};